### PR TITLE
cleanup build warnings

### PR DESCRIPTION
**Pull request by antiochp**
Took some time to clean up some `cargo build` warnings - let me know if you think is worth spending a bit of time on. 

I'm taking some time to get familiar with the code and would like to contribute if I can.

Ideally these will all run cleanly without warnings - 

- [x] `cargo build -p grin_api`
- [x] `cargo test -p grin_api`
- [x] `cargo build -p grin_chain`
- [x] `cargo test -p grin_chain`
- [x] `cargo build -p grin_core`
- [x] `cargo test -p grin_core`
- [x] `cargo build -p grin_p2p`
- [x] `cargo test -p grin_p2p`
- [x] `cargo build -p grin_pool`
- [x] `cargo test -p grin_pool`
- [x] `cargo build -p grin_config`
- [x] `cargo test -p grin_config` <- not actively in use?
- [x] `cargo build -p grin_grin`
- [x] `cargo test -p grin_grin`
- [x] `src`
- [x] `util`
- [x] `wallet`

### CODE REVIEW

**Comment by ignopeverell** [comment]
Definitely worth it and welcome. Could you just reconcile the different cleanups in a single PR though? I can just wait to merge until you have most of it covered.

**Comment by antiochp** [comment]
I think we're almost there. `wallet` is still throwing out a bunch of warning but I think that's the last one to go.

**Comment by antiochp** [comment]
Am I right in assuming there is some instability in the `TEST_DIR=grin` tests on CI?
There's an issue or discussion around this I think?

**Comment by antiochp** [comment]
@ignopeverell I think this is good to go, rebased against master, all tests passing.

**Pull request merged**
