### PR TITLE
Add missing values to config file for pool config

### PR DESCRIPTION
**Pull request by casey**
It looks like the current config is missing a few values. I picked random values, since I didn't know what was reasonable.

### CODE REVIEW

**Comment by ignopeverell** [comment]
Weren't the defaults here properly picked up?

https://github.com/ignopeverell/grin/blob/master/pool/src/types.rs#L43

**Comment by casey** [comment]
I think not, I got this error when building and running a freshly cloned repo:

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
         Running `target/debug/grin`
         thread 'main' panicked at 'Error parsing config file: Error parsing configuration file at /Users/rodarmor/src/grin/grin.toml - missing field `pool_config` for key `server`', src/bin/grin.rs:83:2
         note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by ignopeverell** [comment]
My bad, I mistakenly assumed that the config package would use defaults when a section isn't present. Looks like it can't as serde can't deserialize into a default struct, which is vexing. We don't want to have to specify every single configuration property in the config file.

Ended up fixing this in 0d26daa with default serde tags. A little more boilerplate but does the job.

**Comment by ignopeverell** [comment]
Oh, and thanks for the nice error report!

**Comment by yeastplume** [comment]
I haven't at this particular case in detail, but if you make something in a config struct in the code an Option<T>, then it doesn't need to be present in the config file, and can use the default values.

**Comment by casey** [comment]
Yup, you bet!

**Pull request closed without merging**
