### PR TITLE
Remove secp256k1

### PR DESCRIPTION
**Pull request by antiochp**
* remove secp256k1zkp module
* Cargo.toml specifies external dependency for secp256k1zkp (to be cleaned up)
* use new `verify_from_commit` (`to_pubkey` not currently supported in secp256k1zkp)

TODO -

- [x] cleanup Cargo.toml (currently points at local dir for secp256k1, should be git repo)

Depends on the following PRs being merged first - 
* mimblewimble/secp256k1-zkp#5
* mimblewimble/rust-secp256k1-zkp#2

### CODE REVIEW

**Comment by ignopeverell** [comment]
Merged the 2 PRs for secp256k1-zkp and the Rust wrapper. Feel free to update the Cargo.toml so we can make sure the tests still pass and I'll merge.

Thanks a lot for the cleanup, much better!!

**Comment by knocte** [comment]
Why removing it?

**Comment by ignopeverell** [comment]
See #124

**Comment by antiochp** [comment]
@ignopeverell - good to go. Travis tests are all green.

**Pull request merged**
