### PR TITLE
rename pubkey -> key_id

### PR DESCRIPTION
**Pull request by antiochp**
these are key identifiers, not public keys

### CODE REVIEW

**Comment by ignopeverell** [comment]
Can you merge master into your branch? I merged @yeastplume PR first and it touched quite a fiew files :-)

**Comment by antiochp** [comment]
On it.
My various PRs are all going to cause conflicts with each other as well - apologies for the hassle to come...

**Comment by ignopeverell** [comment]
Might be worth consolidating them as they're all related to the same change?

**Comment by antiochp** [comment]
Sure - if you're happy with one PR I'll do that now.

**Comment by antiochp** [comment]
Closing - consolidated changes into #175

**Pull request closed without merging**
