### PR TITLE
keychain crate (no more secretkeys in core)

### PR DESCRIPTION
**Pull request by antiochp**
Edit: should be good to go - assuming the tests on travis pass this time.

TODO - 
- [x] get grin building
- [x] get all tests passing on travis
- [x] another cleanup pass (unused imports)
- [x] naming - `keychain`? (works for now)
- [x] naming - `Identifier` -> `PublicKey`? (works for now)

This PR introduces a new `grin_keychain` crate to explore the following - 
* Can we encapsulate all private key activity in a small component with limited surface area?
* Could this keychain component be subsequently moved out into a separate process in the future?

Specifically - 
* Can we separate `core` from any knowledge of `secp::key::SecretKey`?
* Can we separate `wallet` (i.e. a public facing wallet receiver) from `ExtendedKey`?

Idea: an `extkey::Identifier` can be thought of as roughly analogous to a public key in bitcoin.
Given an Identifier (pubkey) and a way to derive the corresponding `ExtendedKey` (and `secp SecretKey`) - can we instead pass around a reference to a `keychain` and the `pubkey`?

The keychain api is still taking shape in this PR but it looks approximately like the following (effectively a wrapper around secp + management of the SecretKeys ) - 

```
pub fn derive_pubkey(&self, derivation: u32) -> Result<Identifier, Error>

pub fn commit(&self, amount: u64, pubkey: &Identifier) -> Result<Commitment, Error> 

pub fn range_proof(
    &self,
    amount: u64,
    pubkey: &Identifier,
    commit: Commitment,
) -> Result<RangeProof, Error> 

pub fn blind_sum(&self, blind_sum: &BlindSum) -> Result<BlindingFactor, Error>

pub fn sign(&self, msg: &Message, pubkey: &Identifier) -> Result<Signature, Error>

pub fn sign_with_blinding(
    &self,
    msg: &Message,
    blinding: &BlindingFactor,
) -> Result<Signature, Error> 
```

There is still one place we need to pass a `secp::key::SecretKey` around and that is during txn construction (`sign_with_blinding` in the api above) - we send a partial txn from one wallet to another and this includes the "blinding factor" which is in practice a `secp::key::SecretKey`.

This PR introduces a `BlindingFactor` struct that encapsulates a SecretKey to make it explicit that this is what is being passed around.
This SecretKey does not exist in either wallet (so cannot be derived from a pubkey) as it is a sum of blinding factors involved in the construction of the transaction.

See #140 for some rationale on why I started down this rabbit hole...

I think if we can get to a point where both `core` and `wallet` interact with `keychain` via pubkeys and no longer pass SecretKeys around it will be significantly easier to extract `keychain` out into a separate secure process that the rest of Grin interacts with only when necessary.

Additional benefit - we have a lot less low-level interaction with the secp lib spread throughout the Grin codebase. The interaction points are mainly via `keychain` for txn and block creation. The majority of secp usage now is when verifying txn and blocks are valid.

### CODE REVIEW

**Comment by antiochp** [comment]
Rebased against master and got a bunch of compile errors - working through these.

**Comment by antiochp** [comment]
Hey @ignopeverell - thoughts/comments on this?
This gets us to a point where we can take `keychain` and put it in a separate process.
Neither `wallet` nor `core` need to access extended_keys or secret_keys directly and that secret_keys can remain exclusively in the keychain process.

**Comment by antiochp** [comment]
cc @yeastplume and @apoelstra

**Comment by ignopeverell** [comment]
Just had a look at the code changes, I like it. Cleans up a fair amount of stuff from core and makes our various key manipulations more elegant.

**Comment by yeastplume** [comment]
Yes, I think this is a good first step to isolate the private keys. 

Should probably merge sooner rather than later due to the number of files changed.

**Comment by antiochp** [comment]
@ignopeverell - if we're good with the naming (and everything else in here) then this is good to go.
All tests in travis are green.
I've done reasonably extensive testing locally - mining, sending coins to wallet etc.

**Pull request merged**
