### PR TITLE
Bind to services to all interfaces rather than loopback

### PR DESCRIPTION
**Pull request by yeastplume**
The p2p and endpoints were binding to 127.0.0.1, i.e. the loopback adapter, and not accessible from outside machines. I think we're going to need a way to explicitly specify the adapter to bind to, but this just solves the issue for now to allow to test multi-machine setups via docker.

### CODE REVIEW

**Comment by dandcg** [comment]
Hi, can this change applied to the wallet receiver as well?

**Comment by yeastplume** [comment]
I've applied it to all receivers/listeners throughout, including the wallet.

**Comment by dandcg** [comment]
Ok thanks that's great news.

**Comment by yeastplume** [comment]
Just clarifying, this will make services accessible on all interfaces, not just the default, so if this is merged we should ensure another issue is put up immediately to keep track of the need to configure what IP address or interface the services will bind to.

**Comment by ignopeverell** [comment]
@yeastplume thanks and yes, it should be configurable and I believe the default should be loopback (especially for the wallet stuff).

**Pull request merged**
